feat: support page component
ice-lab/iceworks-cli pull request #17
Opened 2020-08-17 13:56 UTC by sspku-yqLiu

2020-08-20 03:40 UTC, alvinhui commented on packages/iceworks-cli/src/template/initMaterial/package.json.ejs
> +    "pageTemplate": "ice-react-ts-page-material-template-beta"
这里不应该有 pageTemplate，参见：https://github.com/ice-lab/material-templates/pull/24#issuecomment-676937160

2020-08-20 03:42 UTC, alvinhui commented on packages/iceworks-cli/src/command/init/addSingleMaterial.ts
> +const PAGE_CATEGORIES = [
我建议页面的分类如果没有好的划分法的话，可以简单地先划分为：

- Basic
- Others

2020-08-20 03:49 UTC, alvinhui commented on packages/build-plugin-template/src/ejsRenderDir.js
> +/* eslint-disable */
这里哪怕是用 js 重新实现一遍 https://github.com/ice-lab/iceworks-cli/blob/master/packages/iceworks-cli/src/command/init/ejsRenderDir.ts
也不应该直接用编译后的代码

2020-08-20 06:12 UTC, alvinhui commented on packages/iceworks-cli/src/command/init/addSingleMaterial.ts
> +        default: 'intro component',
intro page

2020-08-20 06:14 UTC, alvinhui commented on packages/iceworks-cli/src/command/generate/index.ts
> +    ['block', 'component', 'scaffold','page'].map((item) => {
注意一下代码风格，逗号后面添加空格。

2020-08-20 06:15 UTC, alvinhui commented on packages/iceworks-cli/src/command/add/index.ts
> +      choices: ['block', 'component', 'scaffold','page'],
注意一下代码风格

2020-08-20 06:15 UTC, alvinhui commented on packages/iceworks-cli/bin/iceworks.js
> +    if (materialType && ['scaffold', 'block', 'component','page'].indexOf(materialType) === -1) {
注意一下代码风格

2020-08-20 06:16 UTC, alvinhui commented on packages/build-plugin-template/src/template/page.entry.js
> +console.log(Page);
删除不必要的 debug 代码

2020-08-20 06:38 UTC, sspku-yqLiu commented
第二轮修改完成，请查收

2020-08-20 06:51 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +        .add(/node_modules(?!.+page.entry.js)/);
这里需要判断一下物料类型

2020-08-20 06:53 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +          '@/block': usingTemplate?
这里需要根据物料类型来使用 alias

2020-08-20 06:54 UTC, alvinhui commented on packages/build-plugin-block/package.json
> +    "underscore-template-loader": "^1.1.0"
这个依赖没有使用到？

2020-08-20 06:55 UTC, alvinhui commented on packages/build-plugin-block/package.json
> +    "webpack": "^4.44.1"
加这个依赖的目的是？

2020-08-20 06:56 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +module.exports = ({ context, log, registerTask,registerUserConfig,onGetWebpackConfig,onGetJestConfig },userConfig) => {
代码风格更新一下

2020-08-20 06:58 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +    config.plugin('HotModuleReplacementPlugin').use(webpack.HotModuleReplacementPlugin);
加这个的作用是？

2020-08-20 06:59 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRenderDir.js
> +module.exports = async function(dir ,options) {
代码风格

2020-08-20 07:00 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +}
代码风格

2020-08-20 07:01 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +const originEjsRenderDir = require('./ejsRenderDir');
ejsRenderDir

2020-08-20 07:04 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +  // 之后我们遍从 .tmp 中的 index 进行读取。
这个注释没看明白

2020-08-20 07:06 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +    const mockData = require(path.join(rootDir,'config','mock'));
这里要做一下容错，如果没有这个文件的时候需要 catch 并忽略错误。

2020-08-20 07:08 UTC, alvinhui commented
代码风格关注一下，reviewed

2020-08-20 07:19 UTC, sspku-yqLiu commented on packages/build-plugin-block/src/index.js
> +          '@/block': usingTemplate?
考虑到未来 block 也可能使用 template 的情况，建议这样进行判断。
现在 page 级物料的 build.json 里面都配置了 usingTemplate

2020-08-20 07:20 UTC, sspku-yqLiu commented on packages/build-plugin-block/package.json
> +    "webpack": "^4.44.1"
方便进行调试。否则回报那天在群里讨论的 webpack bug。

2020-08-20 07:25 UTC, sspku-yqLiu commented on packages/build-plugin-block/src/index.js
> +  // 之后我们遍从 .tmp 中的 index 进行读取。
是这样的 代码入口在 @/block。它使用 alias 链接用户代码。
对于没有使用模板的，应该链接到 src/index.tsx
对于使用模板的，应该链接到 .tmp/index.tsx

我将注释改成了这样
  // ejs 模板通过接下来的步骤渲染至 .tmp 文件夹。
  // 之后我们将 @/block 重定位到 .tep 文件夹
  // 这样就引入了经过模拟数据渲染的代码。

2020-08-20 08:10 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +    // add exclude rule for compile template/ice.page.entry.js
add exclude rule for compile template/ice.page(block).entry.js

2020-08-20 08:12 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +/* eslint-disable global-require */
eslint-disable 写成一行

2020-08-20 08:17 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +        .add(new RegExp(`node_modules(?!.+${materialType || 'block'}.entry.js)`));
这里不需要更新，见上面的 entry 设定，沿用 block.entry.js 

需要理解当前 buld-plugin-block 的调试流程。

2020-08-20 08:20 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +      log.error('cannot get mock data', err);
这里 warn 就好了吧？mock 不是必要的

2020-08-20 08:22 UTC, alvinhui commented on packages/iceworks-cli/.vscode/launch.json
> +}
这个文件有用到吗？

2020-08-20 08:23 UTC, alvinhui commented
reviewed， CC @大果

2020-08-20 08:25 UTC, sspku-yqLiu commented on packages/iceworks-cli/.vscode/launch.json
> +}
进行这样的配置后，在调试文件中添加：
"debug":"node --inspect-brk=5858 path/to/iceworks.js [command]",
可以使用断点调试,
如果不需要可以删除掉。

2020-08-20 08:28 UTC, sspku-yqLiu commented on packages/build-plugin-block/src/index.js
> +      log.error('cannot get mock data', err);
这个对应了两种情况，
如果是第一次没有读取到 mock data 就无法生成编译后的文件。无法进行加载
如果是更新之后没有读取到 mock data ,无法生成编译后文件，但是可以保留上一次编译的文件，可以进行加载。
我觉得第一种情况很致命，所以使用了 error

2020-08-20 08:38 UTC, sspku-yqLiu commented on packages/iceworks-cli/.vscode/launch.json
> +  // 3. enjoy Breakpoint Debugging in this project
添加了使用说明。

2020-08-20 08:41 UTC, alvinhui commented on packages/build-plugin-block/src/index.js
> +    // add exclude rule for compile template/ice.page.entry.js
这个注释的改动是错误的

2020-08-20 08:43 UTC, sspku-yqLiu commented
第三轮修改完成，请查收。

2020-08-20 09:44 UTC, imsobear requested changes

2020-08-20 09:44 UTC, imsobear commented on packages/build-plugin-block/src/ejsRender.js
> +};
这个文件封装的必要性是？

2020-08-20 09:44 UTC, imsobear commented on packages/build-plugin-block/src/template/block.entry.js
> +ReactDOM.render(<Block />, mountNode);
在根目录加一个 examples/material-page 的实例，内容就针对 build-pugin-block 的新 feature

2020-08-20 09:44 UTC, imsobear commented on packages/iceworks-cli/bin/iceworks.js
> +    );
这个功能好像失效了，顺便 check 下

2020-08-20 11:53 UTC, imsobear commented on packages/iceworks-cli/src/command/init/addSingleMaterial.ts
> +  options.useEjsTemplate = materialType === 'page';
可以去除了

2020-08-20 11:53 UTC, imsobear commented on packages/iceworks-cli/bin/iceworks.js
> +checkIceworksVersion();
这是个异步方法，需要  await 下

2020-08-20 11:53 UTC, imsobear commented on packages/build-plugin-block/src/ejsRender.js
> +  fse.ensureDir(targetDir);
同步异步问题好好理解下，类似错误有点多

2020-08-20 11:53 UTC, imsobear commented on packages/build-plugin-block/src/ejsRender.js
> +    await ejsRenderDir(targetDir, variables).then();
await ().then() 是什么用法？

2020-08-20 11:53 UTC, imsobear commented on packages/build-plugin-block/src/ejsRender.js
> +const ejsRenderDir= async function (dir, options) {
明显的格式问题

2020-08-20 11:53 UTC, imsobear commented on packages/build-plugin-block/src/examples/material-page.js
> +ReactDOM.render(<Page />, mountNode);
examples 放到根目录，跟 packages 同级，完整的 page example

2020-08-20 13:49 UTC, sspku-yqLiu commented on packages/iceworks-cli/bin/iceworks.js
> +checkIceworksVersion();
这个地方处于文件的最外层，不属于任何函数，应该不能使用 await 。
这也许是这个函数被弃用的原因。

2020-08-21 02:09 UTC, alvinhui commented on packages/iceworks-cli/bin/iceworks.js
> +checkIceworksVersion();
为什么这个 PR 里面添加了这个函数的调用？

2020-08-21 02:11 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +  fse.copySync(sourceDir, targetDir);
既然是在异步函数内，为什么不调用该函数的异步版本？

2020-08-21 02:14 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +    ejs.renderFile(filepath, options, (err, result) => {
这种情况可以用 http://nodejs.cn/api/util.html#util_util_promisify_original 函数将 ejs.renderFile 转换一下

2020-08-21 02:19 UTC, alvinhui commented on examples/material-page/README.md.ejs
> +# <%= name %>
这里需要的是 page material 的示例，而不是 page material 的模板

2020-08-21 02:19 UTC, alvinhui commented on examples/material-page/build.json
> +      {
代码风格参考第 10 行代码的写法

2020-08-21 02:26 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +      if (/\.ejs$/.test(filepath)) {
注意我们的后缀名判断是 ._ejs

2020-08-21 02:27 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +      resolve(newFilepath);
这种情况直接使用 fes.rename API 就好了

http://nodejs.cn/api/fs.html#fs_fs_rename_oldpath_newpath_callback

2020-08-21 02:28 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +function renderFile(filepath, options) {
这个方法看一下改成 async 函数，内部都调用异步方法。

2020-08-21 02:30 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +          .then(() => {
直接 .then(resolve). catch(reject)

2020-08-21 02:36 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +const ejsRenderDir = async function (dir, options) {
第二个参数应该叫 data，参考 ejs.renderFile 中对于第二个参数的命名 https://github.com/mde/ejs#basic-usage

2020-08-21 02:37 UTC, alvinhui commented
reviewed

2020-08-21 05:19 UTC, sspku-yqLiu commented on packages/iceworks-cli/bin/iceworks.js
> +checkIceworksVersion();
因为之前说到这个函数失效的问题 尝试在这里添加了调用

2020-08-21 06:24 UTC, sspku-yqLiu commented
> reviewed

上述问题已改正，请查收。

2020-08-21 06:30 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +  return asyncRenderFile(filepath, options).then(
这里为啥不 await 。。。

2020-08-21 06:31 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +  return asyncRenderFile(filepath, options).then(
为了打印后面的日志？如果是的话，try..catch... 就 OK 了

2020-08-21 06:36 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +async function renderFile(filepath, options, log) {
renderFile 的第二个参数应该要命名为 data

2020-08-21 06:59 UTC, alvinhui commented on packages/build-plugin-block/src/ejsRender.js
> +}
```js
async function renderFile(filepath, data, log) {
  const asyncRenderFile = util.promisify(ejs.renderFile);
  try{
    if (/\.ejs$/.test(filepath)) {
      const content = await asyncRenderFile(filepath, data)
      const targetFilePath = filepath.replace(/\.ejs$/, '');
      await fse.rename(filepath, targetFilePath);
      await fse.writeFile(targetFilePath, content);
    }
  } catch (err) {
    log.error('RenderError', err);
  }
}
```

2020-08-21 08:09 UTC, merged